### ISSUE TITLE
tkinter

### ISSUE THREAD

**Issue by canbuyukburc** [JustOneOther/GCI-Practice#10]
can@Monster:/mnt/d/IT/python/GCI-Practice$ python3 main.py
Please make sure you have all packages installed
If you do, please send the following information to #bugs in Damsel's server:
<class 'ModuleNotFoundError'> | ("No module named 'tkinter'",)

**Comment by JustOneOther** [comment]
Tkinter is included with the python 3.11 standard library, you'll need to manually install it if you built your own python.
