### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by canbuyukburc** [JustOneOther/GCI-Practice#8]
can@Monster:/mnt/d/IT/python/GCI-Practice$ python3 setup.py
Verifying installation (checking if files exist)
main.py : True
Scripts/__init__.py : True
Scripts/GCI_structures.py : True
Scripts/tk_objects.py : True
Scripts/tts_sr.py : True
Resources/callsigns.txt : True
Resources/config.toml : True
Resources/lang_model/0889.dic : True
Resources/lang_model/0889.lm : True
Resources/lang_model/0889.log_pronounce : True
Resources/lang_model/0889.sent : True
Resources/lang_model/0889.vocab : True
Done!

Checking platform and python version
Python should be version 3.11.x or later
Traceback (most recent call last):
  File "/mnt/d/IT/python/GCI-Practice/setup.py", line 39, in <module>
    raise AssertionError()
AssertionError

**Comment by JustOneOther** [comment]
Make sure that you're running python version 3.11.x, it raises that when it detects an earlier version

**Comment by canbuyukburc** [comment]
Python version was wrong on my side, sorry closing
