### ISSUE TITLE
requirements install

### ISSUE THREAD

**Issue by canbuyukburc** [JustOneOther/GCI-Practice#9]
can@Monster:/mnt/d/IT/python/GCI-Practice$ pip3 install -r requirements.txt
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting comtypes==1.1.14
  Using cached comtypes-1.1.14-py2.py3-none-any.whl (172 kB)
Collecting pocketsphinx==5.0.0
  Using cached pocketsphinx-5.0.0.tar.gz (33.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting PyAudio==0.2.13
  Using cached PyAudio-0.2.13.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pypiwin32==223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting pyttsx3==2.90
  Using cached pyttsx3-2.90-py3-none-any.whl (39 kB)
ERROR: Could not find a version that satisfies the requirement pywin32==306
ERROR: No matching distribution found for pywin32==306

**Comment by JustOneOther** [comment]
What OS are you on? I developed this for windows, it may not work on other systems.

**Comment by canbuyukburc** [comment]
Python version was wrong on my side, sorry closing
